require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

install! 'cocoapods',
    :deterministic_uuids => false

target 'firebasern' do
  config = use_native_modules!

  rn_maps_path = '../node_modules/react-native-maps'
  permissions_path = '../node_modules/react-native-permissions/ios'


  pod 'Plaid', '~>2.3.1'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'



  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"


  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"

  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
    # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient/BVLinearGradient.podspec'

  # pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios/RNCPushNotificationIOS.podspec'
  # Pods for firebasern
  # pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  # pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  # pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  # pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  # pod 'React', :path => '../node_modules/react-native/'
  # pod 'React-Core', :path => '../node_modules/react-native/'
  # pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  # pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  # pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  # pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  # pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  # pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  # pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  # pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  # pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  # pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  # pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  # pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  # pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  # pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  # pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  # pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  # pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  # pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  # pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  # pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  

  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  # pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )  
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true


  pod 'react-native-text-input-mask', :path => '../node_modules/react-native-text-input-mask'

  pod 'react-native-plaid-link-sdk', :path => '../node_modules/react-native-plaid-link-sdk'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  target 'firebasernTests' do
    inherit! :complete
    # Pods for testing
  end

 # you should disable the next line.
 #  use_flipper!()
 post_install do |installer|
   react_native_post_install(installer)
 end
target 'firebasern-tvOS' do
  # Pods for firebasern-tvOS
end
  target 'firebasern-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
